name: Sync GitHub issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@1.6
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
          ado_project: '${{ secrets.ADO_PROJECT }}'
          ado_area_path: '${{ secrets.ADO_AREA_PATH }}'
          ado_iteration_path: '${{ secrets.ADO_ITERATION_PATH }}'
          ado_wit: "Product Backlog Item"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: false
